import { Picture } from './picture';

export const PICTURES: Picture[] = [
  { id: 1, imgs: '/assets/images/handdraw/classicart1.jpg',
name:'открыть оригинал', classtyle: '' },
  { id: 2, imgs: '/assets/images/handdraw/classicart2.jpg',
  name:'открыть оригинал', classtyle: '' },
  { id: 3, imgs: '/assets/images/handdraw/classicart3.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 4, imgs: '/assets/images/handdraw/classicart4.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 5, imgs: '/assets/images/handdraw/classicart5.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 6, imgs: '/assets/images/handdraw/classicart6.jpg' ,
  name:'открыть оригинал', classtyle: ''},
  { id: 7, imgs: '/assets/images/handdraw/classicart7.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 8, imgs: '/assets/images/handdraw/classicart8.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  
  { id: 9, imgs: '/assets/images/handdraw/classicart9.jpg' ,
  name:'открыть оригинал' , classtyle: ''},
  { id: 7, imgs: '/assets/images/handdraw/classicart7.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 8, imgs: '/assets/images/handdraw/classicart8.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 7, imgs: '/assets/images/handdraw/classicart7.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 8, imgs: '/assets/images/handdraw/classicart8.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 7, imgs: '/assets/images/handdraw/classicart7.jpg' ,
  name:'открыть оригинал', classtyle: '' },
  { id: 8, imgs: '/assets/images/handdraw/classicart8.jpg' ,
  name:'открыть оригинал', classtyle: '' }
];